name: 'wait'

on:
  pull_request:
    branches:
      - main
      - master
      - 'releases/*'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tidbcloud/wait-for-tidbcloud-branch@v0
        id: wait-for-branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publicKey: ${{ secrets.TIDB_CLOUD_PUBLIC_KEY }}
          privateKey: ${{ secrets.TIDB_CLOUD_PRIVATE_KEY }}
          addMask: false
          env: dev
    outputs:
      username: ${{ steps.wait-for-branch.outputs.username }}
      host: ${{ steps.wait-for-branch.outputs.host }}
      password: ${{ steps.wait-for-branch.outputs.password }}

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Use the output
        run: |
          echo "The host is ${{ needs.setup.outputs.host }}"
          echo "The username is ${{ needs.setup.outputs.username }}"
          echo '::add-mask::${{ needs.setup.outputs.password }}'
          echo "The password is ${{ needs.setup.outputs.password }}"